#!/bin/bash

echo "Updating the system"
apt-get update -y
apt-get upgrade -y

sudo apt-get install -y git python \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -


echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list

sudo apt-get update

echo "Installing Mongo"

sudo apt-get install -y mongodb-org

rm /etc/mongod.conf -f

echo "# mongod.conf

# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# where to write logging data.
systemLog:
  destination: file
  logAppend: true
  path: /var/log/mongodb/mongod.log

# Where and how to store data.
storage:
  dbPath: /var/lib/mongo
  journal:
    enabled: true
#  engine:
#  wiredTiger:

# how the process runs
processManagement:
  fork: true  # fork and run in background
  pidFilePath: /var/run/mongodb/mongod.pid  # location of pidfile
  timeZoneInfo: /usr/share/zoneinfo

# network interfaces
net:
  port: 27017
  bindIp: 0.0.0.0  # Enter 0.0.0.0,:: to bind to all IPv4 and IPv6 addresses or, alternatively, use the net.bindIpAll setting.


#security:

#operationProfiling:

replication:
   replSetName: "rocketchat"

#sharding:

## Enterprise-Only Options

#auditLog:

#snmp:
" >> /etc/mongod.conf

sudo mkdir /var/lib/mongo
sudo chown mongodb:mongodb /var/lib/mongo
sudo  mkdir /var/run/mongodb
sudo chown mongodb:mongodb /var/run/mongodb

sudo service mongod start
