#!/bin/bash

echo "Updating the system"
sudo apt-get update -y
sudo apt-get upgrade -y


curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -


sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

sudo apt-get update -y

sudo apt-get install -y \
    python \
    docker-ce \
    docker-ce-cli \
    containerd.io \
    nfs-common

sudo service docker start

sudo groupadd docker
sudo gpasswd -a ubuntu docker
newgrp docker 

sudo mkdir -p -m777 /mnt/efs/rocketchat

sudo apt-get install nginx -y

sudo service nginx start

sudo service nginx stop

sudo rm /etc/nginx/nginx.conf -f

echo "# For more information on configuration, see:
#   * Official English Documentation: http://nginx.org/en/docs/
#   * Official Russian Documentation: http://nginx.org/ru/docs/

user www-data;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

# Load dynamic modules. See /usr/share/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format  main  '\$remote_addr - \$remote_user [\$time_local] "\$request" '
                      '\$status \$body_bytes_sent "\$http_referer" '
                      '"\$http_user_agent" "\$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    include /etc/nginx/conf.d/*.conf;

server {
listen 80;
server_name rocketchat.toastedbuns.co.uk;
location / {
    proxy_pass http://localhost:3000/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host \$http_host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forward-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forward-Proto http;
    proxy_set_header X-Nginx-Proxy true;
    proxy_redirect off;
}
}
}
"  |  sudo tee -a  /etc/nginx/nginx.conf > /dev/null

sudo service nginx restart


# sudo docker run -v uploads:/app/uploads -e PORT=3000 -e ROOT_URL=http://rocketchat.toastedbuns.co.uk -e MONGO_URL=mongodb://ec2-34-244-243-171.eu-west-1.compute.amazonaws.com:27017,ec2-34-244-243-171.eu-west-1.compute.amazonaws.com:27017/rocketchat?replicaSet=rocketchat -e MONGO_OPLOG_URL=mongodb://ec2-34-244-243-171.eu-west-1.compute.amazonaws.com:27017,ec2-34-244-243-171.eu-west-1.compute.amazonaws.com:27017/local?replicaSet=rocketchat -e Accounts_UseDNSDomainCHeck=True -p 3000:3000 rocket.chat:latest


