#!/bin/bash

while read line;
do
  echo $line | awk '{ print $2 }' >> public_dns_updated.txt;
  sleep 2s
done < ../public_dnss.txt

cp install_mongo.tpl install_mongo

x=0

while read line;
do
  variable="host_$x"
  sed -i "s/$variable/$line/g" install_mongo
  ((x++))
done < public_dns_updated.txt


mongo_url=""

y=0
while read line;
do
  if [ "$y" == "1" ]; then
    mongo_url_final="$mongo_url,$line:27017"
  else
    mongo_url="$line:27017"
  fi
((y++))
done < public_dns_updated.txt

echo "mongodb://$mongo_url_final" >> connection_url.txt
export MONGO_URL=$mongo_url_final


